name: Build & Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout to current code
        uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm i

      - name: Building public assets
        run: npm run build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.LS_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.LS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload build files
        run: rsync -azv  ./public/* ${{ secrets.LS_USER }}@${{ secrets.LS_HOST }}:/var/www/laravel/public/

      - name: Pull code to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LS_HOST }}
          username: ${{ secrets.LS_USER }}
          key: ${{ secrets.LS_PRIVATE_KEY }}
          script: |
            cd /var/www/laravel
            git add .
            git commit -m "commits on server"
            git pull origin main
            composer install --no-dev
            php artisan migrate --force
            php artisan optimize:clear
