name: Test Password Hash

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Plain text password to hash'
        required: true

jobs:
  test-hash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Test Password Hash
      run: |
        php artisan tinker --execute="
        \$plainPassword = '${{ github.event.inputs.password }}';
        \$hash = \Illuminate\Support\Facades\Hash::make(\$plainPassword);
        echo 'Plain password: ' . \$plainPassword . PHP_EOL;
        echo 'Hashed password: ' . \$hash . PHP_EOL;
        echo 'Verification test: ' . (\Illuminate\Support\Facades\Hash::check(\$plainPassword, \$hash) ? 'Passed' : 'Failed') . PHP_EOL;
        "
